name: CI

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize, assigned, edited]
#     branches: [ "master" ]

jobs:
  trigger-cm:
    runs-on: ubuntu-latest
    steps:
      - name: CM Trigger
        id: cm-mohammed
        uses: mohammedbabelly/cm-action@v3
        with:
          cm-token: ${{ secrets.CM_TOKEN }}
          app-id: '6315a13cd08d3f4a6708a798'
          workflow-id: 'ios-method-1'
          branch: 'master'
#         env:
#           CCI_TOKEN: ${{ secrets.CM_TOKEN }}          
